services:
  - type: web
    name: evaluation-system-backend
    env: docker
    region: oregon
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5000
